In [8]:
import torch

In [9]:
x = torch.arange(12)

In [10]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
x.shape

torch.Size([12])

In [12]:
x.numel

<function Tensor.numel>

In [13]:
x.numel()

12

In [14]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
torch.tensor(([[1,2,3],[2,3,4]])).shape

torch.Size([2, 3])

In [19]:
torch.tensor(([[[1,2,3],[2,3,4]]])).shape

torch.Size([1, 2, 3])

In [22]:
x = torch.tensor([1,2,4,8])
y = torch.tensor([2,3,4,5])

In [23]:
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3,  5,  8, 13]),
 tensor([-1, -1,  0,  3]),
 tensor([ 2,  6, 16, 40]),
 tensor([0.5000, 0.6667, 1.0000, 1.6000]),
 tensor([    1,     8,   256, 32768]))

In [24]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [26]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

In [33]:
# 合并张量 dim=0--行维度 dim=1--列维度
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [30]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [34]:
x.sum()

tensor(66.)

In [36]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [37]:
# 广播机制，补齐维度，复制前一行或列的内容
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [38]:
x[-1]

tensor([ 8.,  9., 10., 11.])

In [39]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
before = id(y)
before

3140260950880

In [41]:
y = y + x
id(y)

3140283263152

In [42]:
# 原地操作
id(y)

3140283263152

In [43]:
y[:] = y+x
id(y)

3140283263152

In [44]:
z = torch.zeros_like(y)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
y

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [46]:
y.item()

ValueError: only one element tensors can be converted to Python scalars

In [47]:
A = x.numpy()

In [48]:
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [49]:
# 将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [51]:
a = torch.arange(2).reshape((2,1))
b = torch.arange(8).reshape((2,4))
# 维度按照右对齐后，需要复制的维度只有一行/列或者为空，其余行/列不需要复制。
a + b

tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])

In [52]:
# 数据预处理
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 列名
    f.write('2,NA,106000\n')  # 列名
    f.write('4,NA,178100\n')  # 列名
    f.write('NA,NA,140000\n')  # 列名


In [72]:
import pandas as pd
data = pd.read_csv('../data/house_tiny.csv')

In [73]:
print(data)
data
type(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


pandas.core.frame.DataFrame

In [89]:
# 处理缺失数据 -- 插值或删除
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]

In [81]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [76]:
# 将字符类型转换为数字
inputs = pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [78]:
#  转换为tensor
inputs = torch.tensor(inputs.to_numpy(dtype=float))
outputs = torch.tensor(outputs.to_numpy(dtype=float))
inputs,outputs

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [82]:
# 删除缺失值最多的列
inputs,outputs

(   NumRooms Alley
 0       3.0  Pave
 1       2.0   NaN
 2       4.0   NaN
 3       3.0   NaN,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64)

In [90]:
inputs

NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN

In [92]:
x = inputs.isna().sum()
x.argmax()

1

In [103]:
inputs = inputs.drop(columns=x.index[x.argmax()])

In [104]:
# 转换为张量格式
inputs

NumRooms
0       NaN
1       2.0
2       4.0
3       NaN

In [95]:
type(outputs)

pandas.core.series.Series

In [96]:
type(inputs)

pandas.core.frame.DataFrame

In [106]:
inputs = torch.tensor(inputs.to_numpy(dtype=float))
outputs = torch.tensor(outputs.to_numpy(dtype=float))
inputs,outputs

AttributeError: 'Tensor' object has no attribute 'to_numpy'

In [123]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [124]:
x[3]

tensor(3)

In [125]:
# 统计行数
len(x)

4

In [126]:
x.size()

torch.Size([4])

In [127]:
A = torch.arange(12).reshape((3,4))

In [128]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [129]:
A.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [130]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [131]:
a = torch.arange(24).reshape((2,3,4))
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [137]:
A = torch.arange(20,dtype=torch.float32).reshape((5,4))
B = A
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [138]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [139]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [140]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [144]:
A.shape,A.sum()
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [146]:
A_sum_axis0 = A.sum(axis=0)

In [143]:
A_sum_axis0

tensor([40., 45., 50., 55.])

In [151]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1

tensor([ 6., 22., 38., 54., 70.])

In [148]:
# 保持轴数不变
A_sum_axis1 = A.sum(axis=1,keepdims=True)
A_sum_axis1

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [159]:
A / A_sum_axis1

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [158]:
A_sum_axis1 = A_sum_axis1.reshape((5,1))

In [160]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [161]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [162]:
x

tensor([0., 1., 2., 3.])

In [167]:
y = torch.ones((4),dtype = torch.float32)

In [168]:
y

tensor([1., 1., 1., 1.])

In [169]:
torch.dot(x,y)

tensor(6.)

In [170]:
torch.sum(x * y)

tensor(6.)

In [171]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [172]:
# 矩阵向量积
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [173]:
B = torch.ones((4,3))
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [174]:
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [175]:
# 计算L2范数 -- 距离
u = torch.tensor([3.0,-4])
u.norm()

tensor(5.)

In [176]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [177]:
# 矩阵的范数 F范数
torch.norm(torch.ones((4,9)))

tensor(6.)

In [178]:
a = torch.ones((2,5,4))
a.sum().shape

torch.Size([])

In [179]:
a.sum(axis=[0,2]).shape

torch.Size([5])

In [181]:
a.sum(axis=[0,2],keepdims=True).shape

torch.Size([1, 5, 1])