In [182]:
import torch

In [184]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [188]:
# 对x求的梯度进行保存
x.requires_grad_(True)
print(x.grad)

None


In [190]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [191]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [192]:
x.grad == 4 * x

tensor([True, True, True, True])

In [204]:
# 默认情况，Pytorch会累计梯度，清除梯度
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [205]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [208]:
x.grad.zero_()
y = x * x

In [209]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [213]:
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [214]:
x.grad.zero_()
y = x * x
u = y.detach()
u

tensor([0., 1., 4., 9.])

In [215]:
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [216]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [217]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [218]:
# 计算控制流梯度
a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()
a.grad

tensor(102400.)

In [219]:
a.grad == d / a

tensor(True)

In [220]:
a.grad

tensor(102400.)