In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [2]:
net = nn.Sequential(nn.Linear(8,128), CenteredLayer())
Y = net(torch.rand(4,8))
Y.mean()

tensor(-4.1910e-09, grad_fn=<MeanBackward0>)

In [5]:
# 带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
# 实例化MyLinear类
linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[-2.4687, -0.1185, -0.9114],
        [ 0.8066,  1.6828, -1.5246],
        [ 0.2587, -2.2132,  1.4125],
        [-0.4033,  0.6193, -0.2960],
        [ 1.1272,  1.7309,  1.7100]], requires_grad=True)

In [7]:
linear(torch.randn(2,5))

tensor([[0.0000, 3.1614, 0.0000],
        [0.1149, 1.1574, 0.1000]])

In [8]:
net = nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[0.],
        [0.]])