In [24]:
import torch
from d2l import torch as d2l

def corr2d_multi_in(X,K):
    return sum(d2l.corr2d(X,K) for X,K in zip(X,K))

In [25]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])
print(X.size(),K.size())
corr2d_multi_in(X, K)

torch.Size([2, 3, 3]) torch.Size([2, 2, 2])


tensor([[ 56.,  72.],
        [104., 120.]])

In [26]:
def corr2d_multi_in_out(X,K):
    return torch.stack([corr2d_multi_in(X,k) for k in K], 0)

In [28]:
K = torch.stack((K,K+1,K+2),0)
K

tensor([[[[[0., 1.],
           [2., 3.]],

          [[1., 2.],
           [3., 4.]]],


         [[[1., 2.],
           [3., 4.]],

          [[2., 3.],
           [4., 5.]]],


         [[[2., 3.],
           [4., 5.]],

          [[3., 4.],
           [5., 6.]]]],



        [[[[1., 2.],
           [3., 4.]],

          [[2., 3.],
           [4., 5.]]],


         [[[2., 3.],
           [4., 5.]],

          [[3., 4.],
           [5., 6.]]],


         [[[3., 4.],
           [5., 6.]],

          [[4., 5.],
           [6., 7.]]]],



        [[[[2., 3.],
           [4., 5.]],

          [[3., 4.],
           [5., 6.]]],


         [[[3., 4.],
           [5., 6.]],

          [[4., 5.],
           [6., 7.]]],


         [[[4., 5.],
           [6., 7.]],

          [[5., 6.],
           [7., 8.]]]]])

In [21]:
corr2d_multi_in_out(X,K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])